version: "3.9"
services:
  lrmAxon:
    hostname: 'lrm-axon'
    container_name: 'lrm-axon'
    image: axoniq/axonserver:2023.1.1-jdk-17-dev
    ports:
      - '8024:8024'
      - '8124:8124'
      - '8224:8224'
    environment:
      - TZ=Asia/Bangkok
    restart: always
  lrmPostgres:
    hostname: 'lrm-postgres'
    container_name: 'lrm-postgres'
    image: postgres:11
    ports:
      - "5430:5432"
    environment:
      - TZ=Asia/Bangkok
      - POSTGRES_PASSWORD=1234
    restart: always
